# Generated by Django 4.0.3 on 2022-04-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField()),
                ('fiscalDateEnding', models.TextField()),
                ('reportedEPS', models.TextField()),
                ('surprise', models.TextField()),
                ('surprisePercentage', models.TextField()),
            ],
        ),
    ]
