# Generated by Django 4.0.3 on 2022-04-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0002_earning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earning',
            name='surprise',
            field=models.TextField(default='Unavailable'),
        ),
        migrations.AlterField(
            model_name='earning',
            name='surprisePercentage',
            field=models.TextField(default='Unavailable'),
        ),
    ]
