# Generated by Django 4.0.3 on 2022-04-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0003_alter_earning_surprise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField()),
                ('assetType', models.TextField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('CIK', models.TextField()),
                ('exchange', models.TextField()),
                ('currency', models.TextField()),
                ('country', models.TextField()),
                ('sector', models.TextField()),
                ('industry', models.TextField()),
                ('address', models.TextField()),
                ('fiscalYearEnd', models.TextField()),
                ('latestQuarter', models.TextField()),
                ('marketCapitalization', models.TextField()),
                ('EBITDA', models.TextField()),
                ('PERatio', models.TextField()),
                ('PEGRatio', models.TextField()),
                ('bookValue', models.TextField()),
                ('dividendPerShare', models.TextField()),
                ('dividendYield', models.TextField()),
                ('EPS', models.TextField()),
                ('revenuePerShareTTM', models.TextField()),
                ('profitMargin', models.TextField()),
                ('operatingMarginTTM', models.TextField()),
                ('returnOnAssetsTTM', models.TextField()),
                ('returnOnEquityTTM', models.TextField()),
                ('revenueTTM', models.TextField()),
                ('grossProfitTTM', models.TextField()),
                ('dilutedEPSTTM', models.TextField()),
                ('quarterlyEarningsGrowthYOY', models.TextField()),
                ('quarterlyRevenueGrowthYOY', models.TextField()),
                ('analystTargetPrice', models.TextField()),
                ('trailingPE', models.TextField()),
                ('forwardPE', models.TextField()),
                ('priceToSalesRatioTTM', models.TextField()),
                ('priceToBookRatio', models.TextField()),
                ('EVToRevenue', models.TextField()),
                ('EVToEBITDA', models.TextField()),
                ('beta', models.TextField()),
                ('_52WeekHigh', models.TextField()),
                ('_52WeekLow', models.TextField()),
                ('_50DayMovingAverage', models.TextField()),
                ('_200DayMovingAverage', models.TextField()),
                ('sharesOutstanding', models.TextField()),
                ('dividendDate', models.TextField()),
                ('exDividendDate', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='earning',
            name='surprise',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='earning',
            name='surprisePercentage',
            field=models.TextField(),
        ),
    ]
