# Generated by Django 4.0.3 on 2022-04-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0006_annual_balance_sheet_annual_cash_flow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annual_balance_sheet',
            name='symbol',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annual_cash_flow',
            name='symbol',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quarterly_balance_sheet',
            name='symbol',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quarterly_cash_flow',
            name='symbol',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
