from django.contrib import admin

# Register your models here.

from .models import *

admin.site.register([
    Quarterly_Real_GDP,
    Annual_Real_GDP,
    Real_GDP_Per_Capita,
    Daily_3month_Treasury_Yield,
    Weekly_3month_Treasury_Yield,
    Monthly_3month_Treasury_Yield,
    Daily_2year_Treasury_Yield,
    Weekly_2year_Treasury_Yield,
    Monthly_2year_Treasury_Yield,
    Daily_5year_Treasury_Yield,
    Weekly_5year_Treasury_Yield,
    Monthly_5year_Treasury_Yield,
    Daily_7year_Treasury_Yield,
    Weekly_7year_Treasury_Yield,
    Monthly_7year_Treasury_Yield,
    Daily_10year_Treasury_Yield,
    Weekly_10year_Treasury_Yield,
    Monthly_10year_Treasury_Yield,
    Daily_30year_Treasury_Yield,
    Weekly_30year_Treasury_Yield,
    Monthly_30year_Treasury_Yield,
    Daily_Federal_Funds_Rate,
    Weekly_Federal_Funds_Rate,
    Monthly_Federal_Funds_Rate,
    Monthly_Cpi,
    Semiannual_Cpi,
    Inflation,
    Inflation_Expectation,
    Consumer_Sentiment,
    Retail_Sales,
    Durables,
    Unemployment,
    Nonfarm_Payroll,
    Annual_Income_Statement,
    Quarterly_Income_Statement,
    Annual_Balance_Sheet,
    Quarterly_Balance_Sheet,
    Annual_Cash_Flow,
    Quarterly_Cash_Flow,
    Earning,
    Overview,
    Earning_Calendar,
])