from django.urls import path
from . import views

urlpatterns = [
    # Economic Indicators
    path('', views.getRoutes, name='routes'),
    path('economic_calendar/', views.getEconomicCalendar, name='economic_calendar'),
    path('quarterly_real_gdp/', views.getQuarterlyRealGdp, name='quarterly_real_gdp'),
    path('annual_real_gdp/', views.getAnnualRealGdp, name='annual_real_gdp'),
    path('real_gdp_per_capita/', views.getRealGdpPerCapita, name='real_gdp_per_capita'),
    path('daily_3month_treasury_yield/', views.getDaily3monthTreasuryYield, name='daily_3month_treasury_yield'),
    path('weekly_3month_treasury_yield/', views.getWeekly3monthTreasuryYield, name='weekly_3month_treasury_yield'),
    path('monthly_3month_treasury_yield/', views.getMonthly3monthTreasuryYield, name='monthly_3month_treasury_yield'),
    path('daily_2year_treasury_yield/', views.getDaily2yearTreasuryYield, name='daily_2year_treasury_yield'),
    path('weekly_2year_treasury_yield/', views.getWeekly2yearTreasuryYield, name='weekly_2year_treasury_yield'),
    path('monthly_2year_treasury_yield/', views.getMonthly2yearTreasuryYield, name='monthly_2year_treasury_yield'),
    path('daily_5year_treasury_yield/', views.getDaily5yearTreasuryYield, name='daily_5year_treasury_yield'),
    path('weekly_5year_treasury_yield/', views.getWeekly5yearTreasuryYield, name='weekly_5year_treasury_yield'),
    path('monthly_5year_treasury_yield/', views.getMonthly5yearTreasuryYield, name='monthly_5year_treasury_yield'),
    path('daily_7year_treasury_yield/', views.getDaily7yearTreasuryYield, name='daily_7year_treasury_yield'),
    path('weekly_7year_treasury_yield/', views.getWeekly7yearTreasuryYield, name='weekly_7year_treasury_yield'),
    path('monthly_7year_treasury_yield/', views.getMonthly7yearTreasuryYield, name='monthly_7year_treasury_yield'),
    path('daily_10year_treasury_yield/', views.getDaily10yearTreasuryYield, name='daily_10year_treasury_yield'),
    path('weekly_10year_treasury_yield/', views.getWeekly10yearTreasuryYield, name='weekly_10year_treasury_yield'),
    path('monthly_10year_treasury_yield/', views.getMonthly10yearTreasuryYield, name='monthly_10year_treasury_yield'),
    path('daily_30year_treasury_yield/', views.getDaily30yearTreasuryYield, name='daily_30year_treasury_yield'),
    path('weekly_30year_treasury_yield/', views.getWeekly30yearTreasuryYield, name='weekly_30year_treasury_yield'),
    path('monthly_30year_treasury_yield/', views.getMonthly30yearTreasuryYield, name='monthly_30year_treasury_yield'),
    path('daily_federal_funds_rate/', views.getDailyFederalFundsRate, name='daily_federal_funds_rate'),
    path('weekly_federal_funds_rate/', views.getWeeklyFederalFundsRate, name='weekly_federal_funds_rate'),
    path('monthly_federal_funds_rate/', views.getMonthlyFederalFundsRate, name='monthly_federal_funds_rate'),
    path('monthly_cpi/', views.getMonthlyCpi, name='monthly_cpi'),
    path('semiannual_cpi/', views.getSemiannualCpi, name='semiannual_cpi'),
    path('inflation/', views.getInflation, name='inflation'),
    path('inflation_expectation/', views.getInflationExpectation, name='inflation_expectation'),
    path('consumer_sentiment/', views.getConsumerSentiment, name='consumer_sentiment'),
    path('retail_sales/', views.getRetailSales, name='retail_sales'),
    path('durables/', views.getDurables, name='durables'),
    path('unemployment/', views.getUnemployment, name='unemployment'),
    path('nonfarm_payroll/', views.getNonfarmPayroll, name='nonfarm_payroll'),

    # Company Fundamentals
    path('annual_income_statement/<str:pk>/', views.getAnnualIncomeStatement, name='annual_income_statement'),
    path('quarterly_income_statement/<str:pk>/', views.getQuarterlyIncomeStatement, name='quarterly_income_statement'),
    path('annual_balance_sheet/<str:pk>/', views.getAnnualBalanceSheet, name='annual_balance_sheet'),
    path('quarterly_balance_sheet/<str:pk>/', views.getQuarterlyBalanceSheet, name='quarterly_balance_sheet'),
    path('annual_cash_flow/<str:pk>/', views.getAnnualCashFlow, name='annual_cash_flow'),
    path('quarterly_cash_flow/<str:pk>/', views.getQuarterlyCashFlow, name='quarterly_cash_flow'),
    path('earning/<str:pk>/', views.getEarning, name='earning'),
    path('overview/<str:pk>/', views.getOverview, name='overview'),
    path('earning_calendar/', views.getEarningCalendar, name='earning_calendar'),
    path('earning_calendar/<str:pk>/', views.getIndividualEarningCalendar, name='individual_earning_calendar'),
    path('news/<str:pk>/', views.getIndividualNews, name='individual_news'),
    path('options_contracts/<str:pk>/', views.getOptionsContracts, name='options_contracts'),
    path('single_option_contract/<str:pk1>/<str:pk2>/', views.getSingleOptionContract, name='single_option_contract'),
]